### ISSUE TITLE
Value transform method `preset` has no docs

### ISSUE THREAD

**Issue by adas172002** [pqina/flip#17]
I am not able to find documentation for transform component `preset`, which is used eg. in flip example `flip-master/example/index.html`. There are many methods in the docs on https://pqina.nl/tick/#value-transforms, but this one is missing.

**Comment by rikschennink** [comment]
It's used to create an easier way to apply a certain transform to a value.

This is the handler for the `abs` transform.

```js
export default () => (value, cb) => cb(Math.abs(value));
```

This is the handler for the `preset` transform.

```js
export default (...presets) => (value, cb, instance) => 
    cb(
        value.map(
            (v, index) => instance.getPreset(presets[index])(v, instance.getConstants(), instance)
        )
    );
```

1. It receives all the defined presets in the transform (for example `'d', 'h', 'm', 's'`). 
2. Then in the order of the value array it'll get the preset for that value from the Tick instance preset array.

The value would be something like [0, 11, 3, 20] where `0` is days, `11` is hours, etc.

It'll thus load preset `'d'` for `0`, which is this preset:

```js
d:(value, constants) => (
		transformDurationUnit(
			value,
			constants.DAY_SINGULAR,
			constants.DAY_PLURAL,
			365
		)
),
```

The value returned is passed on to the next node.

You can add your own presets with `setPreset(key, value)` and then you can use it in your tick template.

Honestly the preset/constant functions were only added to make creating date timers more easy. So that's kinda why they're not documented at this point.

**Comment by adas172002** [comment]
Thanks, it seems `preset` is specific to how flip is handling date timers. I was looking for documentation because example file is using `preset(d, h, m, s)` and for my project I just needed hour, minute and second. I removed `d` and it didn't work, so I tried to the docs and found nothing. Only after reading about option object `format: ['h', 'm', 's']` I managed to make it work.

**Comment by rikschennink** [comment]
@adas172002 Yes it maps directly to the format, so both should have the same keys.

**Comment by adas172002** [comment]
Great, I hope others will benefit from this information. 

Closing the issue, thanks.
